import dotenv from "dotenv"
dotenv.config();


const CLIENT_ID = process.env.CLIENT_ID;
const CLIENT_SECRET = process.env.CLIENT_SECRET;
const REDIRECT_URI = process.env.REDIRECT_URI;
const REFRESH_TOKEN = process.env.REFRESH_TOKEN;
const USER_EMAIL = process.env.USER_EMAIL;
const USER_NAME = process.env.USER_EMAIL;
const RECEPIENTS_EMAIL = process.env.RECEPIENTS_EMAIL;
const AUTHORIZATION_TOKEN = process.env.AUTHORIZATION_TOKEN;

const REDIS_HOST = process.env.REDIS_HOST;
const REDIS_PORT = process.env.REDIS_PORT;
const REDIS_PASSWORD = process.env.REDIS_PASSWORD;
const REDIS_USERNAME = process.env.REDIS_USERNAME;

const REDIS_HOST_LOCAL = process.env.REDIS_HOST_LOCAL;
const REDIS_PORT_LOCAL = process.env.REDIS_PORT_LOCAL;
const REDIS_PASSWORD_LOCAL = process.env.REDIS_PASSWORD_LOCAL;

const DB_URI = process.env.DB_URI;
const SLACK_WEBHOOK = process.env.SLACK_WEBHOOK;

const NODE_ENV = process.env.NODE_ENV;

const TELEGRAM_TOKEN = process.env.TELEGRAM_TOKEN;
const TELEGRAM_CHATID = process.env.TELEGRAM_CHATID;
const ACCESS_SECRET = process.env.JWT_ACCESS_SECRET;
const REFRESH_SECRET = process.env.JWT_REFRESH_SECRET;

const ORIGIN_DEVELOP = process.env.ORIGIN_HOST_LOCAL;
const ORIGIN_DEVELOP_PATH = process.env.ORIGIN_HOST_LOCAL_PATH;
const ORIGIN_PROD = process.env.ORIGIN_HOST_PROD;

export {
  CLIENT_ID,
  CLIENT_SECRET,
  REDIRECT_URI,
  REFRESH_TOKEN,
  USER_EMAIL,
  USER_NAME,
  RECEPIENTS_EMAIL,
  REDIS_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  REDIS_USERNAME,
  REDIS_HOST_LOCAL,
  REDIS_PORT_LOCAL,
  REDIS_PASSWORD_LOCAL,
  DB_URI,
  SLACK_WEBHOOK,
  AUTHORIZATION_TOKEN,
  NODE_ENV,
  TELEGRAM_TOKEN,
  TELEGRAM_CHATID,
  ACCESS_SECRET,
  REFRESH_SECRET,
  ORIGIN_DEVELOP,
  ORIGIN_DEVELOP_PATH,
  ORIGIN_PROD,
};
